---------------------------- MODULE ReplayWindow ----------------------------
(***************************************************************************)
(* Extended Rung 4 of the sudo-proxy formalisation roadmap: the temporal   *)
(* freshness <-> replay-retention WINDOW-SIZING property that the sibling   *)
(* `ApprovalStateMachine` model deliberately hides.                        *)
(*                                                                         *)
(* That model abstracts the clock to a boolean and models the replay set   *)
(* (`seen`) as never evicting -- "conservative for ReplayImpossible". This *)
(* model restores the concrete (but small, abstract) clock and the real    *)
(* TTL eviction, and proves the genuinely temporal claim the daemon relies  *)
(* on: a captured request cannot evade replay-dedup by waiting for its id   *)
(* to be evicted while STILL passing the freshness gate.                   *)
(*                                                                         *)
(* The two real-code windows (src/server.rs):                              *)
(*   MAX_REQUEST_AGE   = 60s   -- freshness gate (check_freshness)          *)
(*   REPLAY_RETENTION  = 120s  -- seen-id eviction TTL (SeenIds::evict_stale*)
(* are modelled by the small constants Freshness / Retention; only their   *)
(* RELATIONSHIP matters, not the absolute seconds (see README).            *)
(*                                                                         *)
(* The PlusCal algorithm below is the source of truth; the TLC-checkable   *)
(* translation between BEGIN/END TRANSLATION is generated by `pcal.trans`  *)
(* and committed alongside. If you edit the PlusCal, re-run pcal.trans and  *)
(* commit both.                                                            *)
(*                                                                         *)
(* Faithfulness ledger, the window arithmetic, the negative-control recipe,*)
(* and the two findings this model surfaced live in proofs/tla/README.md.  *)
(***************************************************************************)
EXTENDS Integers, FiniteSets

CONSTANTS Ids,        \* the bounded set of request ids; the cfg uses {r1}
          Freshness,  \* freshness window (abstract units); real code: 60s
          Retention,  \* replay-retention TTL; real code: 120s = 2*Freshness
          MaxTime     \* clock horizon; bounds the state space, keeps it finite

(* --algorithm ReplayWindow

variables
    \* An abstract wall clock; advanced only by the Tick branch, bounded at
    \* MaxTime so the reachable state space is finite.
    clock = 0,

    \* Replay dedup (SeenIds), now with eviction MODELLED: each remembered id
    \* carries its insertion time (and the request timestamp, used only by the
    \* NC2 mutation). Faithful to the HashSet + VecDeque<(id, Instant)> pair.
    seen = {},

    \* The single captured request we track (Ids = {r1}: the per-id property;
    \* the two-distinct-ids interaction is the sibling model's job). `origTs` is
    \* the original timestamp -- the bytes an attacker captures and replays.
    origExists = FALSE,
    origId     = CHOOSE i \in Ids : TRUE,
    origTs     = 0,
    origAccAt  = 0,    \* the clock value when the original was first accepted

    \* ---- monitor (violation) flags ----
    \* A PAST-dated captured request re-executed (replay slipped dedup). The
    \* window-sizing theorem says this is impossible once Retention >= Freshness.
    vReplay = FALSE,
    \* A FUTURE-dated captured request re-executed after eviction. This one IS
    \* reachable -- the finding: parse_age clamps future timestamps to age 0
    \* (server.rs:146) with no upper cap, so a request dated beyond Retention
    \* into the future is replayable regardless of how large Retention is.
    vFutureReplay = FALSE,

    \* The request on the wire and the busy handshake with the daemon.
    busy  = FALSE,
    inReq = [id |-> CHOOSE i \in Ids : TRUE, ts |-> 0];

define
    \* Faithful to parse_age: a future-dated timestamp (ts > now) is clamped to
    \* age 0 and so always passes; otherwise age = now - ts must be <= Freshness.
    FreshAt(ts) == IF ts > clock THEN TRUE ELSE clock - ts <= Freshness

    \* evict_stale keyed on INSERTION time (the faithful rule). The NC2 mutation
    \* changes `rec.insertedAt` to `rec.ts` -- evicting by the request timestamp,
    \* the exact bug the REPLAY_RETENTION code comment warns against.
    Live(rec) == ~(clock - rec.insertedAt > Retention)
    Evicted   == { rec \in seen : Live(rec) }
end define;

\* The environment / attacker + the honest client, fully nondeterministic.
process Env = "env"
begin
EnvLoop:
    while TRUE do
        await ~busy;
        either
            \* Time advances (between handled requests; handling is atomic --
            \* faithful: check_freshness runs at handler ENTRY, server.rs:499).
            await clock < MaxTime;
            clock := clock + 1;
        or
            \* The one genuine request for this id. Its timestamp is free over
            \* the whole horizon, so it covers both an honest fresh request and
            \* a (clock-skewed / crafted) FUTURE-dated one.
            await ~origExists;
            with i \in Ids, t \in 0..MaxTime do
                inReq := [id |-> i, ts |-> t];
                busy  := TRUE;
            end with;
        or
            \* The attacker replays the CAPTURED BYTES: same id, same timestamp.
            \* (Minting a fresh timestamp under an existing nonce id is not
            \* replay -- ids are random; that case is out of scope.)
            await origExists;
            inReq := [id |-> origId, ts |-> origTs];
            busy  := TRUE;
        end either;
    end while;
end process;

\* The daemon: freshness gate, then the eviction-aware dedup (try_insert), then
\* dispatch. One request handled to completion atomically.
process Daemon = "daemon"
begin
Handle:
    while TRUE do
        await busy;
        if ~FreshAt(inReq.ts) then
            skip;                          \* freshness gate -> reject; try_insert not called
        elsif \E rec \in Evicted : rec.id = inReq.id then
            \* try_insert: evict_stale ran, id still present -> duplicate, reject.
            seen := Evicted;
        else
            \* Accept: evict, then insert stamped with the current clock.
            seen := Evicted \union {[id |-> inReq.id, insertedAt |-> clock, ts |-> inReq.ts]};
            if origExists then
                \* A replay slipped through dedup -- record which kind.
                if origTs <= origAccAt then
                    vReplay := TRUE;       \* PAST capture: the theorem forbids this
                else
                    vFutureReplay := TRUE; \* FUTURE capture: the documented finding
                end if;
            else
                origExists := TRUE;
                origId     := inReq.id;
                origTs     := inReq.ts;
                origAccAt  := clock;
            end if;
        end if;
        busy := FALSE;
    end while;
end process;

end algorithm; *)
\* BEGIN TRANSLATION
VARIABLES clock, seen, origExists, origId, origTs, origAccAt, vReplay, 
          vFutureReplay, busy, inReq

(* define statement *)
FreshAt(ts) == IF ts > clock THEN TRUE ELSE clock - ts <= Freshness




Live(rec) == ~(clock - rec.insertedAt > Retention)
Evicted   == { rec \in seen : Live(rec) }


vars == << clock, seen, origExists, origId, origTs, origAccAt, vReplay, 
           vFutureReplay, busy, inReq >>

ProcSet == {"env"} \cup {"daemon"}

Init == (* Global variables *)
        /\ clock = 0
        /\ seen = {}
        /\ origExists = FALSE
        /\ origId = (CHOOSE i \in Ids : TRUE)
        /\ origTs = 0
        /\ origAccAt = 0
        /\ vReplay = FALSE
        /\ vFutureReplay = FALSE
        /\ busy = FALSE
        /\ inReq = [id |-> CHOOSE i \in Ids : TRUE, ts |-> 0]

Env == /\ ~busy
       /\ \/ /\ clock < MaxTime
             /\ clock' = clock + 1
             /\ UNCHANGED <<busy, inReq>>
          \/ /\ ~origExists
             /\ \E i \in Ids:
                  \E t \in 0..MaxTime:
                    /\ inReq' = [id |-> i, ts |-> t]
                    /\ busy' = TRUE
             /\ clock' = clock
          \/ /\ origExists
             /\ inReq' = [id |-> origId, ts |-> origTs]
             /\ busy' = TRUE
             /\ clock' = clock
       /\ UNCHANGED << seen, origExists, origId, origTs, origAccAt, vReplay, 
                       vFutureReplay >>

Daemon == /\ busy
          /\ IF ~FreshAt(inReq.ts)
                THEN /\ TRUE
                     /\ UNCHANGED << seen, origExists, origId, origTs, 
                                     origAccAt, vReplay, vFutureReplay >>
                ELSE /\ IF \E rec \in Evicted : rec.id = inReq.id
                           THEN /\ seen' = Evicted
                                /\ UNCHANGED << origExists, origId, origTs, 
                                                origAccAt, vReplay, 
                                                vFutureReplay >>
                           ELSE /\ seen' = (Evicted \union {[id |-> inReq.id, insertedAt |-> clock, ts |-> inReq.ts]})
                                /\ IF origExists
                                      THEN /\ IF origTs <= origAccAt
                                                 THEN /\ vReplay' = TRUE
                                                      /\ UNCHANGED vFutureReplay
                                                 ELSE /\ vFutureReplay' = TRUE
                                                      /\ UNCHANGED vReplay
                                           /\ UNCHANGED << origExists, origId, 
                                                           origTs, origAccAt >>
                                      ELSE /\ origExists' = TRUE
                                           /\ origId' = inReq.id
                                           /\ origTs' = inReq.ts
                                           /\ origAccAt' = clock
                                           /\ UNCHANGED << vReplay, 
                                                           vFutureReplay >>
          /\ busy' = FALSE
          /\ UNCHANGED << clock, inReq >>

Next == Env \/ Daemon

Spec == Init /\ [][Next]_vars

\* END TRANSLATION

\* ===================== invariants & properties =====================

\* Modeling-hygiene type invariant.
TypeOK ==
    /\ clock \in 0..MaxTime
    /\ seen \subseteq [id : Ids, insertedAt : 0..MaxTime, ts : 0..MaxTime]
    /\ origExists \in BOOLEAN
    /\ origId \in Ids
    /\ origTs \in 0..MaxTime
    /\ origAccAt \in 0..MaxTime
    /\ vReplay \in BOOLEAN
    /\ vFutureReplay \in BOOLEAN
    /\ busy \in BOOLEAN
    /\ inReq \in [id : Ids, ts : 0..MaxTime]

\* THE WINDOW-SIZING THEOREM (holds for Retention >= Freshness; the shipped
\* config has Retention = 2*Freshness): no captured PAST-dated request is ever
\* re-executed. A captured replay cannot win the race between freshness expiry
\* and eviction -- by the time its id could be evicted, its fixed timestamp has
\* already aged past the freshness gate.
\*
\* Stated as a monitor (vReplay raised at the re-exec site, exactly like the
\* sibling model's ReplayImpossible) rather than as a `\E rec \in seen` set-
\* membership predicate -- ON PURPOSE. Eviction is LAZY (an id is pruned only
\* inside try_insert) and a replay-accept removes then re-inserts the id in one
\* atomic step, so a membership invariant can never observe the gap; only an
\* event monitor can. This is the same reason the sibling model uses monitors.
PastReplayImpossible == ~vReplay

\* Sanity: the daemon only ever accepts a request that was fresh at acceptance
\* (either future-dated -- clamped to age 0 -- or within the freshness window).
AcceptWasFresh ==
    origExists => (origTs > origAccAt \/ origAccAt - origTs <= Freshness)

\* ----- the future-clamp FINDING (NOT in the committed .cfg) -----
\* This invariant FAILS by design: TLC returns a future-dated counterexample in
\* which a captured request dated beyond Retention into the future is re-executed
\* after its id is evicted. parse_age clamps future timestamps to age 0
\* (server.rs:146) with no upper cap, so such a request keeps passing the
\* freshness gate forever while its id ages out of `seen` -- making it replayable
\* every Retention units regardless of how large Retention is. Add NoFutureReplay
\* to INVARIANTS by hand to reproduce the trace; see README "Finding: future-
\* dated replay".
NoFutureReplay == ~vFutureReplay

=============================================================================
